### ISSUE TITLE
Gazebo Sim

### ISSUE THREAD

**Issue by REGATTE** [carlo98/precision_landing_shaping_RL#4]
Hi, is it possible to run the whole setup locally instead of Docker? If so could you please provide the steps to do so? I'm able to build the WS with `custom_msgs` &  `px4_ros_extended`, but not able to run the next processes according to `launch_train_ddpg.sh`.

**Comment by carlo98** [comment]
Hi! I couldn't make it work on my pc, so I can't provide you with the exact steps:(
I believe that you'll need to install ROS2 dashing and follow the steps available in the Dockerfile, have you already tried this way?

**Comment by REGATTE** [comment]
yea,
I'm running ROS2 Foxy, and I've already installed the dependencies required by Foxy, also installed DDPG separately.

Every time I run the `ros2 run px4_ros_extended ddpg_agent.py -p /use_sim_time:=true` as per `launch_train_ddpg.sh`, the terminal freezes and crashes. Checked for any underlying issues and nothing seems wrong.

**Comment by carlo98** [comment]
I don't know how to help you...I'm sorry. Do you get any error message? I'll try to run all the installation with Foxy and let you know, but it's going to take some time, I've just started a few other things.

**Comment by REGATTE** [comment]
As such, there is no error. The terminal windows just close abruptly. I thought it had something to do with sourcing my `.bash` files as I had a similar issue when I was building px4_ros_com_ros2 WS for PX4 SITL, which wasn't the case. It would be great if you could work through it once if you have the chance.

**Comment by carlo98** [comment]
Hi, I've tried to install foxy and run the code and it works, unfortunately I cannot (do not know how to) do this in my pc without screwing with other installations, so I've done it by preparing another Dockerfile.

I don't think it's going to solve your problem though, because the steps are exactly the same...anyway, if you want to try it, its available in the branch "foxy_install" (I'll merge it with main this evening).

**Comment by REGATTE** [comment]
oh okay. thanks for help.

the following might help to work with foxy and not affect other installations

install foxy, and source it
`source /opt/ros/foxy/setup.bash`

and then source the foxy ws 
`source ~/ws/install/setup.bash`

just comment out the other ros2 source on your ~/.bashrc files by adding a **`#`**.
